version: "3"

networks:
  internal:
    driver: bridge

services:
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/

  # EXPRESSJS instance
  backend:
    container_name: "${BACKEND_CONTAINER_NAME}"
    build: "./backend/"
    volumes:
      - "./backend/app:/opt/backend/app"
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DB_PWD: "${DB_PWD}"
    networks:
      - internal

